title = "Composable CDP"
baseURL = "https://docs.snowplow.io/accelerators/databricks-hightouch-composable-cdp/"

[params]
  description = "Tutorial building a composable CDP using Snowplow, Databricks and Hightouch"
  author = "Snowplow, George Woodhead"
